### PR TITLE
Changed getId() to getSuggestibleId()

### PR DESCRIPTION
**Pull request by bpappin**
This resolves issue #19.

### CODE REVIEW

**Comment by nhibner** [comment]
Can you please fix the compilation issues with the TestMention class? Once that's fixed and tests pass, I'll merge the request.

**Comment by bpappin** [comment]
Oh man, I hate Android Studio, it should have caught that right away. I'll get on it right away.

**Comment by bpappin** [comment]
Hmm, investigated this and you shouldn't be getting those errors, most of them are things like support v4 class missing.

Also, the code for those the classes, MentionSpan and RichEditorView, already contain the import for com.linkedin.android.spyglass.R.

If you look at the code changes (link follows) you can see that the imports were never removed:
https://github.com/bpappin/Spyglass/commit/d07a35553db4666be900b45b0f5e56d47532e2d1

Please check your CI build.

**Comment by nhibner** [comment]
Yeah, for some reason, it reports those symbols as not found (usually related to the R class and the support library). I've spent a little time looking into it, but haven't been able to determine why it gives those warnings. I created an issue to track it (#21) and will give it another look.

The real issue for your code though is in the output you linked, just below the warnings. I think you will just need to update the names of the methods in the TestMention class. Here are the errors I'm referring to:

```
:spyglass:processDebugUnitTestJavaRes UP-TO-DATE
:spyglass:compileDebugUnitTestJava/home/travis/build/linkedin/Spyglass/spyglass/src/test/java/com/linkedin/android/spyglass/mentions/TestMention.java:23: error: TestMention is not abstract and does not override abstract method getSuggestiblePrimaryText() in Suggestible
public class TestMention implements Mentionable {
       ^
/home/travis/build/linkedin/Spyglass/spyglass/src/test/java/com/linkedin/android/spyglass/mentions/TestMention.java:31: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/travis/build/linkedin/Spyglass/spyglass/src/test/java/com/linkedin/android/spyglass/mentions/TestMention.java:36: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors
 FAILED
```

**Comment by bpappin** [comment]
OK, got it, running against the CI now.

**Comment by nhibner** [comment]
Thanks! We'll publish a new version on maven within the next day or two (will also include #18).

**Pull request merged**
